// Mixed KV: turbo5 K + turbo4 V (sibling of the kturbo6-vturbo4 preset)

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_TURBO5_0, GGML_TYPE_TURBO4_0);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_TURBO5_0, GGML_TYPE_TURBO4_0);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_TURBO5_0, GGML_TYPE_TURBO4_0);
