#!/usr/bin/env bash
# build-release.sh — produce a release tarball of ollama-tq for one platform.
#
# What ships in the tarball:
#   bin/ollama-tq                            # the fork's binary
#   lib/ollama/cuda_v12/libggml-cuda.so      # the CUDA backend (FA-vec kernels)
#   lib/ollama/cuda_v12/libggml-base.so*     # paired with the CUDA backend
#   lib/ollama/libggml-cpu-*.so              # CPU-variant fallbacks
#   share/ollama-tq/ollama-serve-tq          # the canonical serve wrapper
#   share/ollama-tq/ollama-tq.service        # systemd unit template
#   share/ollama-tq/calibration/manifest.json
#   share/ollama-tq/calibration/*.json       # bundled adaptive entries
#   VERSION
#   README.md  (a small one pointing at the install script)
#
# What's intentionally NOT shipped:
#   build/lib/ollama/libggml-cuda.so (the flat .so) — its presence at runtime
#     causes the double-load SIGSEGV documented in TURBOQUANT-DEBUG-LOG.md
#     2026-04-30 "Bug 3". Ship only the cuda_v12/ subdir; the flat .so exists
#     in the build tree only for in-process eval (calibration tooling).
#
# Output: dist/ollama-tq-<version>-linux-x86_64-cuda12.tar.gz + .sha256
#
# Usage:
#   scripts/build-release.sh [-v <version>] [--skip-build]
#     -v <version>   override version string (default: git describe --always)
#     --skip-build   reuse the existing binary at the expected path

set -euo pipefail

repo_root() {
  cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd
}

ROOT="$(repo_root)"
cd "$ROOT"

VERSION="$(git describe --always --dirty 2>/dev/null || echo "dev-$(date +%Y%m%d)")"
SKIP_BUILD=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    -v) VERSION="$2"; shift 2 ;;
    --skip-build) SKIP_BUILD=1; shift ;;
    -h|--help) sed -n '2,/^set -euo pipefail/p' "$0" | sed '$d' >&2; exit 0 ;;
    *) echo "error: unknown flag: $1" >&2; exit 2 ;;
  esac
done

PLATFORM="linux-x86_64-cuda12"
DIST="$ROOT/dist"
STAGE="$DIST/ollama-tq-${VERSION}-${PLATFORM}"
BINARY="$ROOT/build/ollama-tq"
LIBDIR="$ROOT/build/lib/ollama"
TARBALL="$DIST/ollama-tq-${VERSION}-${PLATFORM}.tar.gz"

echo "=== build-release.sh ==="
echo "  version:  $VERSION"
echo "  platform: $PLATFORM"
echo "  stage:    $STAGE"
echo "  tarball:  $TARBALL"
echo

# 1. Build the binary if needed.
if [[ "$SKIP_BUILD" == "1" && -x "$BINARY" ]]; then
  echo "[1/5] Reusing existing binary at $BINARY"
else
  echo "[1/5] Building ollama-tq..."
  mkdir -p build
  GOCACHE="${GOCACHE:-/tmp/ollama-build-gocache}" \
    CGO_ENABLED=1 \
    go build -trimpath -o "$BINARY" .
fi
ls -la "$BINARY"
echo

# 2. Verify the libdir has the CUDA backend (must be present from a prior
#    `go generate ./...` or upstream build).
if [[ ! -f "$LIBDIR/cuda_v12/libggml-cuda.so" ]]; then
  echo "error: $LIBDIR/cuda_v12/libggml-cuda.so missing." >&2
  echo "       Run the upstream build to populate build/lib/ollama first" >&2
  echo "       (e.g. cmake --build build for Ollama's ggml subproject)." >&2
  exit 1
fi

# 3. Stage layout.
echo "[2/5] Staging $STAGE"
rm -rf "$STAGE"
mkdir -p \
  "$STAGE/bin" \
  "$STAGE/lib/ollama" \
  "$STAGE/share/ollama-tq/calibration"

cp "$BINARY" "$STAGE/bin/ollama-tq"
chmod +x "$STAGE/bin/ollama-tq"

# Copy the cuda_v12/ subdir entirely.
cp -a "$LIBDIR/cuda_v12" "$STAGE/lib/ollama/"

# CPU-variant backends (so non-AVX-512 hosts still load).
for so in "$LIBDIR"/libggml-cpu-*.so; do
  cp -a "$so" "$STAGE/lib/ollama/"
done

# DO NOT copy build/lib/ollama/libggml-base.so or build/lib/ollama/libggml-cuda.so
# from the top level — those are for in-process eval. The cuda_v12/ subdir
# contains its own libggml-base.so.0.* siblings that the runtime discovers.
# (Verified: cuda_v12/ ships its own ggml-base.)

# 4. Drop the wrapper script + systemd unit + bundled calibrations.
echo "[3/5] Bundling wrapper, systemd unit, calibrations"

cat > "$STAGE/share/ollama-tq/ollama-serve-tq" <<'EOF'
#!/usr/bin/env bash
# ollama-serve-tq — start the TurboQuant Ollama server with sensible defaults.
# Generated by build-release.sh. Edit freely; the installer will not overwrite
# this file on update unless --force is passed.
set -euo pipefail

OLLAMA_BIN="${OLLAMA_BIN:-$HOME/.local/bin/ollama-tq}"
[[ -x "$OLLAMA_BIN" ]] || { echo "error: $OLLAMA_BIN not found or not executable" >&2; exit 1; }

# turboquant-adaptive resolves per (architecture, file_type, head_dim) against
# the bundled calibration manifest at
#   $HOME/.local/share/ollama-tq/calibration/manifest.json
# When a model has a calibrated entry the runtime applies its base K/V cache
# type and per-layer key overrides. Otherwise it falls back to kq8-vturbo4
# (the model-agnostic safe split). Both require flash attention and the Go
# engine.
OLLAMA_HOST="${OLLAMA_HOST:-0.0.0.0:8001}" \
OLLAMA_MODELS="${OLLAMA_MODELS:-$HOME/.ollama/models}" \
OLLAMA_KV_CACHE_TYPE="${OLLAMA_KV_CACHE_TYPE:-turboquant-adaptive}" \
OLLAMA_FLASH_ATTENTION="${OLLAMA_FLASH_ATTENTION:-1}" \
OLLAMA_NEW_ENGINE="${OLLAMA_NEW_ENGINE:-1}" \
OLLAMA_KEEP_ALIVE="${OLLAMA_KEEP_ALIVE:--1}" \
OLLAMA_CONTEXT_LENGTH="${OLLAMA_CONTEXT_LENGTH:-65536}" \
OLLAMA_MAX_LOADED_MODELS="${OLLAMA_MAX_LOADED_MODELS:-1}" \
OLLAMA_NUM_GPU="${OLLAMA_NUM_GPU:-999}" \
  exec "$OLLAMA_BIN" serve
EOF
chmod +x "$STAGE/share/ollama-tq/ollama-serve-tq"

cat > "$STAGE/share/ollama-tq/ollama-tq.service" <<'EOF'
# ollama-tq.service — drop into /etc/systemd/system/ and `systemctl enable --now`.
# Edit Environment= lines if you want a different port or device order.
[Unit]
Description=Ollama TurboQuant (turbo4 KV cache)
After=network-online.target
Wants=network-online.target
# Conflict with upstream ollama.service so they don't race for GPU memory.
Conflicts=ollama.service

[Service]
Type=simple
User=__USER__
Group=__USER__

# Defaults are visible to both GPUs in PCI order. Override CUDA_VISIBLE_DEVICES
# if you only want a subset.
Environment="CUDA_DEVICE_ORDER=PCI_BUS_ID"
Environment="OLLAMA_MODELS=/home/__USER__/.ollama/models"

ExecStart=/home/__USER__/.local/bin/ollama-serve-tq

Restart=on-failure
RestartSec=15

StandardOutput=journal
StandardError=journal
SyslogIdentifier=ollama-tq

[Install]
WantedBy=multi-user.target
EOF

# Bundle the manifest + calibration artifacts.
cp "$ROOT/tools/turboquant/calibration/manifest_data/manifest.json" \
   "$STAGE/share/ollama-tq/calibration/"
for f in "$ROOT"/tools/turboquant/calibration/manifest_data/*-adaptive.json; do
  cp "$f" "$STAGE/share/ollama-tq/calibration/"
done

# 5. README + VERSION at the root of the tarball.
echo "[4/5] Writing VERSION + README"
echo "$VERSION" > "$STAGE/VERSION"

cat > "$STAGE/README.md" <<EOF
# ollama-tq $VERSION ($PLATFORM)

Prebuilt TurboQuant-enabled Ollama for Linux x86_64 + CUDA 12.

## Install

\`\`\`bash
tar xzf ollama-tq-${VERSION}-${PLATFORM}.tar.gz
cd ollama-tq-${VERSION}-${PLATFORM}
./install.sh   # if you bundled the installer; otherwise see scripts/install-tq.sh
\`\`\`

Or for a one-shot from a release URL:

\`\`\`bash
curl -fsSL https://raw.githubusercontent.com/pitcany/ollama-turboquant/turboquant/runtime/scripts/install-tq.sh | bash
\`\`\`

## Layout (after extraction)

- \`bin/ollama-tq\` — the binary
- \`lib/ollama/cuda_v12/\` — CUDA backend + base lib
- \`lib/ollama/libggml-cpu-*.so\` — CPU fallback variants
- \`share/ollama-tq/ollama-serve-tq\` — wrapper script with sensible defaults
- \`share/ollama-tq/ollama-tq.service\` — systemd unit template (replace __USER__)
- \`share/ollama-tq/calibration/\` — bundled adaptive calibration manifest

## What this gives you

Per-model KV-cache quantization that holds quality (\`mean_kl < 0.05\` Phase 0
budget) while saving:

- ~62-72% KV memory vs f16 on Causal models (qwen2.5, llama3, gemma3, ...)
- ~57-61% on hybrid Causal+SSM models (qwen3.5/3.6, lfm2, nemotronh)

Run a model and watch \`journalctl -u ollama-tq -f\` for
\`turboquant-adaptive resolved cache_type=...\` confirming the manifest entry
landed. See \`USAGE.md\` in the repo for the full operator guide.
EOF

# 6. Tarball + checksum.
echo "[5/5] Creating $TARBALL + sha256"
tar -C "$DIST" -czf "$TARBALL" "ollama-tq-${VERSION}-${PLATFORM}"
( cd "$DIST" && sha256sum "$(basename "$TARBALL")" > "$(basename "$TARBALL").sha256" )

echo
echo "=== done ==="
ls -la "$TARBALL" "$TARBALL.sha256"
echo
echo "Stage dir kept at $STAGE for inspection. Remove with: rm -rf $STAGE"
echo "Upload tarball with:"
echo "  gh release create $VERSION $TARBALL $TARBALL.sha256 \\"
echo "    --repo pitcany/ollama-turboquant \\"
echo "    --target turboquant/runtime \\"
echo "    --title \"ollama-tq $VERSION\" \\"
echo "    --notes-file <release-notes.md>"
